import { buildSgqr } from "./build";

/**
 * Rehearsed demo codes. Every UEN, SGQR ID and merchant name here is fictional and
 * generated by `buildSgqr`; no real merchant's payload is committed to this repo.
 */
export interface SgqrFixture {
  id: string;
  title: string;
  blurb: string;
  payload: string;
}

export const DEMO_FIXTURES: SgqrFixture[] = [
  {
    id: "kopitiam",
    title: "Ah Hock Kopitiam",
    blurb: "Dynamic code, S$18.50 due",
    payload: buildSgqr({
      dynamic: true,
      payNow: { proxyType: "uen", proxyValue: "202401234K", amountEditable: false },
      sgqr: {
        sgqrId: "000001234567",
        version: "01",
        postalCode: "079903",
        levelNumber: "01",
        unitNumber: "12",
        versionDate: "20260101",
      },
      merchantCategoryCode: "5812",
      amount: "18.50",
      merchantName: "AH HOCK KOPITIAM",
      merchantCity: "Singapore",
      postalCode: "079903",
      additional: { billNumber: "INV20260919", terminalLabel: "POS01" },
    }),
  },
  {
    id: "bookstore",
    title: "Bras Basah Books",
    blurb: "Dynamic code, S$42.00 due",
    payload: buildSgqr({
      dynamic: true,
      payNow: { proxyType: "uen", proxyValue: "199805678M", amountEditable: false },
      sgqr: { sgqrId: "000009876543", version: "01", postalCode: "188064" },
      merchantCategoryCode: "5942",
      amount: "42.00",
      merchantName: "BRAS BASAH BOOKS",
      merchantCity: "Singapore",
      postalCode: "188064",
      additional: { referenceLabel: "ORDER-5521" },
    }),
  },
  {
    id: "hawker",
    title: "Maxwell Hawker Stall 42",
    blurb: "Static code, you enter the amount",
    payload: buildSgqr({
      dynamic: false,
      payNow: { proxyType: "uen", proxyValue: "53401234X", amountEditable: true },
      sgqr: { sgqrId: "000004242424", version: "01", postalCode: "069184" },
      merchantCategoryCode: "5814",
      merchantName: "MAXWELL STALL 42",
      merchantCity: "Singapore",
      postalCode: "069184",
    }),
  },
  {
    id: "unregistered",
    title: "Unregistered merchant",
    blurb: "Valid code, no X Layer address on file",
    payload: buildSgqr({
      dynamic: true,
      payNow: { proxyType: "uen", proxyValue: "201911111A", amountEditable: false },
      merchantCategoryCode: "5999",
      amount: "9.90",
      merchantName: "TAMPINES MINIMART",
      merchantCity: "Singapore",
    }),
  },
];

/** A payload whose checksum has been tampered with, for the parse-error path. */
export const CORRUPT_FIXTURE = (() => {
  const good = DEMO_FIXTURES[0].payload;
  return `${good.slice(0, -4)}0000`;
})();
